import AuthProvider from "./auth/AuthProvider";
import Header from "./components/Header/Header";
import "./globals.css";
import QueryWrapper from "./QueryWrapper";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-full">
        <QueryWrapper>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </QueryWrapper>
      </body>
    </html>
  );
}
